config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'signup'         => 'users#new'
  post   'users/promote'  => 'users#change_admin'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'account_activations/edit'
  resources :account_activations, only: [:edit]

  get    'sessions/new'
  get    'login_as/:id' => 'sessions#login_as'
  get    'login'        => 'sessions#new'
  post   'login'        => 'sessions#create'
  delete 'logout'       => 'sessions#destroy'
  
  get    'users/:user_id/journal_entries' => 'journal_entries#index', as: :journal_entries
  post   'users/:user_id/journal_entries' => 'journal_entries#create'
  get    'users/:user_id/journal_entries/:id' => 'journal_entries#show', as: :journal_entry
  get    'users/:user_id/journal_entries/:id/edit' => 'journal_entries#edit', as: :edit_journal_entry
  patch  'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
#  put    'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
  delete 'users/:user_id/journal_entries/:id' => 'journal_entries#destroy', as: :delete_journal_entry
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  belongs_to :user
  
  def decodeArrowAt(index)
    if index < self.half_round.length
      arr = self.half_round[index]
      if(arr == "T")
        return "10"
      elsif arr === "M" || arr === "X" || arr === "1" || arr === "2" || arr === "3" || arr === "4" || 
                 arr === "5" || arr === "6" || arr === "7" || arr === "8" || arr === "9"
        return arr
      end
    end
    return "_"
  end
  
  def arrowValueAt(index)
    if index < self.half_round.length
      arr = self.half_round[index]
      if(arr == "T" || arr == "X")
        return 10
      elsif arr === "1" || arr === "2" || arr === "3" || arr === "4" || arr === "5" || arr === "6" || arr === "7" || arr === "8" || arr === "9"
        return arr.to_i
      end
    end
    return 0
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  helper_method :sort_column, :sort_direction
  
  def index
    @user = User.find(params[:user_id])
    @journal_entries = @user.journal_entries.order(sort_column + " " + sort_direction).paginate(page: params[:page])
    @journal_entry = JournalEntry.new
  end
  
  def show
    @journal_entry = JournalEntry.find(params[:id])
  end

  def create
    @journal_entry = current_user.journal_entries.build(entry_date: Date.today)
    if @journal_entry.save
      redirect_to edit_journal_entry_url(id: @journal_entry, user_id: current_user)
    else
      redirect_to journal_entries_url(user_id: current_user)
    end
  end
  
  def edit
    @journal_entry = JournalEntry.find(params[:id])
  end
  
  def update
    @journal_entry = JournalEntry.find(params[:id])
    if @journal_entry.update_attributes(journal_entry_params)
      #add_flash_message( :success, t('.update_success') )
      respond_to do |format|
        format.html { redirect_to journal_entries_url(user_id: current_user) }
        format.js
      end
    else
      render 'edit'
    end
  end
  
  def destroy
    JournalEntry.find(params[:id]).destroy
    add_flash_message( :success, "Journal Entry Deleted" )
    redirect_to journal_entries_url(user_id: current_user)
  end
  
  private
    def journal_entry_params
      params.require(:journal_entry).permit(:past_physical_reflection,
                                            :past_mental_reflection,
                                            :goal_progress,
                                            :half_round,
                                            :conditions,
                                            :coach_advice,
                                            :individual_activity_reflection,
                                            :lesson_reflection,
                                            :what_i_did_well_today,
                                            :future_physical_reflection,
                                            :future_mental_reflection,
                                            :entry_date)
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:user_id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    def sort_column
      JournalEntry.column_names.include?(params[:sort]) ? params[:sort] : "entry_date"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/journal_entries/_form_info.html.haml
= f.label :entry_date, "Entry Date", class: 'required' 
.form-inline
  = date_select :journal_entry, :entry_date, {start_year: Date.today.year - 1, end_year: Date.today.year, order: [:month, :day, :year], prompt: true}, {class: "form-control"} 

= f.label :past_physical_reflection, "Physical Practice Reflection for Past Week", class: 'required'
= f.text_area :past_physical_reflection, class: 'form-control' 

= f.label :past_mental_reflection, "Mental Practice Reflection for Past Week", class: 'required'
= f.text_area :past_mental_reflection, class: 'form-control' 

= f.label :goal_progress, "Goal Progress", class: 'required'
= f.text_area :goal_progress, class: 'form-control' 

= f.label :half_round, "Half-Round", class: 'required'
= f.text_field :half_round, class: 'form-control' 

= f.label :conditions, "Weather Conditions", class: 'required'
= f.text_field :conditions, class: 'form-control' 

= f.label :coach_advice, "Coach Advice", class: 'required'
= f.text_area :coach_advice, class: 'form-control' 

= f.label :individual_activity_reflection, "Individual Activity Reflection", class: 'required'
= f.text_area :individual_activity_reflection, class: 'form-control' 

= f.label :lesson_reflection, "Lesson Reflection", class: 'required'
= f.text_area :lesson_reflection, class: 'form-control' 

= f.label :what_i_did_well_today, "What I Did Well Today", class: 'required'
= f.text_area :what_i_did_well_today, class: 'form-control' 

= f.label :future_physical_reflection, "Physical Practice Plan for Next Week", class: 'required'
= f.text_area :future_physical_reflection, class: 'form-control' 

= f.label :future_mental_reflection, "Mental Practice Plan for Next Week", class: 'required'
= f.text_area :future_mental_reflection, class: 'form-control' 

app/views/journal_entries/_journal_entry.html.haml
%tr
  %td.nowrap
    = link_to journal_entry.entry_date, journal_entry_path(id: journal_entry, user_id: current_user)
  %td
    = link_to "edit", edit_journal_entry_path(id: journal_entry, user_id: current_user)
    |
    = link_to "delete", journal_entry_path(id: journal_entry, user_id: current_user), method: :delete, data: { confirm: "Are you sure?" }

app/views/journal_entries/index.html.haml
- provide(:title, "Archer's Journal")
.row
  .col-md-6.col-md-offset-3
    = form_for(@journal_entry) do |f| 
      = render 'shared/error_messages', object: f.object 
      = f.submit "Add New Entry", class: "btn btn-primary" 
    %br
    .panel.generic-panel
      .panel-heading
        %h3.panel-title.center= "Archer's Journal"
      %table.table.center
        %tr
          %th.center= sortable "entry_date", "Date"
          %th.center= "Modify"
        = render @journal_entries || "No Entries"
    .center
      = will_paginate

app/views/journal_entries/show.html.haml
- provide(:title, @journal_entry.entry_date)
.row
  .col-md-6.col-md-offset-3
    .panel.generic-panel
      .panel-heading
        %h3.panel-title.center Journal Entry
      %table.table
        = table_row_helper("Entry Date", @journal_entry.entry_date)
        = table_row_helper("Physical Practice Reflection for Past Week", @journal_entry.past_physical_reflection || "Nothing Entered")
        = table_row_helper("Mental Practice Reflection for Past Week", @journal_entry.past_mental_reflection || "Nothing Entered")
        = table_row_helper("Goal Progress", @journal_entry.goal_progress || "Nothing Entered")
        %tr
          %td 
            %b Half-Round
          %td
            %table.table.table-striped.center
              %thead
                %tr
                  %th.center
                  %th.center #1
                  %th.center #2
                  %th.center #3
                  %th.center End
                  %th.center Run
              %tbody
                %tr#end1
                  %td
                    %b 1
                  %td= @journal_entry.decodeArrowAt(0)
                  %td= @journal_entry.decodeArrowAt(1)
                  %td= @journal_entry.decodeArrowAt(2)
                  %td= end1 = @journal_entry.arrowValueAt(0) + @journal_entry.arrowValueAt(1) + @journal_entry.arrowValueAt(2)
                  %td= end1
                %tr#end2
                  %td
                    %b 2
                  %td= @journal_entry.decodeArrowAt(3)
                  %td= @journal_entry.decodeArrowAt(4)
                  %td= @journal_entry.decodeArrowAt(5)
                  %td= end2 = @journal_entry.arrowValueAt(3) + @journal_entry.arrowValueAt(4) + @journal_entry.arrowValueAt(5)
                  %td= end1 + end2
                %tr#end3
                  %td 
                    %b 3
                  %td= @journal_entry.decodeArrowAt(6)
                  %td= @journal_entry.decodeArrowAt(7)
                  %td= @journal_entry.decodeArrowAt(8)
                  %td= end3 = @journal_entry.arrowValueAt(6) + @journal_entry.arrowValueAt(7) + @journal_entry.arrowValueAt(8)
                  %td= end1 + end2 + end3
                %tr#end4
                  %td 
                    %b 4
                  %td= @journal_entry.decodeArrowAt(9)
                  %td= @journal_entry.decodeArrowAt(10)
                  %td= @journal_entry.decodeArrowAt(11)
                  %td= end4 = @journal_entry.arrowValueAt(9) + @journal_entry.arrowValueAt(10) + @journal_entry.arrowValueAt(11)
                  %td= end1 + end2 + end3 + end4
                %tr#end5
                  %td 
                    %b 5
                  %td= @journal_entry.decodeArrowAt(12)
                  %td= @journal_entry.decodeArrowAt(13)
                  %td= @journal_entry.decodeArrowAt(14)
                  %td= end5 = @journal_entry.arrowValueAt(12) + @journal_entry.arrowValueAt(13) + @journal_entry.arrowValueAt(14)
                  %td= end1 + end2 + end3 + end4 + end5
        = table_row_helper("Weather Conditions", @journal_entry.conditions || "Nothing Entered")
        = table_row_helper("Coach Advice", @journal_entry.coach_advice || "Nothing Entered")
        = table_row_helper("Individual Activity Reflection", @journal_entry.individual_activity_reflection || "Nothing Entered")
        = table_row_helper("Lesson Reflection", @journal_entry.lesson_reflection || "Nothing Entered")
        = table_row_helper("What I Did Well Today", @journal_entry.what_i_did_well_today || "Nothing Entered")
        = table_row_helper("Physical Practice Plan for Next Week", @journal_entry.future_physical_reflection || "Nothing Entered")
        = table_row_helper("Mental Practice Plan for Next Week", @journal_entry.future_mental_reflection || "Nothing Entered")