config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'signup'         => 'users#new'
  post   'users/promote'  => 'users#change_admin'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'account_activations/edit'
  resources :account_activations, only: [:edit]

  get    'sessions/new'
  get    'login_as/:id' => 'sessions#login_as'
  get    'login'        => 'sessions#new'
  post   'login'        => 'sessions#create'
  delete 'logout'       => 'sessions#destroy'
  
  get    'users/:user_id/journal_entries' => 'journal_entries#index', as: :journal_entries
  post   'users/:user_id/journal_entries' => 'journal_entries#create'
  get    'users/:user_id/journal_entries/:id' => 'journal_entries#show', as: :journal_entry
  get    'users/:user_id/journal_entries/:id/edit' => 'journal_entries#edit', as: :edit_journal_entry
  patch  'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
#  put    'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
  delete 'users/:user_id/journal_entries/:id' => 'journal_entries#destroy', as: :delete_journal_entry
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user && @user.activated?
      @user.create_reset_digest
      @user.send_password_reset_email
      add_flash_message( :info, t('.password_reset_sent') )
      redirect_to root_url
    elsif @user && !@user.activated?
      flash.now[:danger] = [t('.account_not_activated')]
      @user.send_new_activation_email
      render 'new'
    else
      flash.now[:danger] = [t('.email_not_found')]
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, t('.empty_error'))
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      add_flash_message( :success, t('.password_reset_confirmation') )
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        add_flash_message( :danger, t('.password_reset_expired') )
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.haml
- provide(:title, t('.title'))
%h1= t('.title')

.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: password_reset_path(params[:id])) do |f| 
      = render 'shared/error_messages', object: f.object

      = hidden_field_tag :email, @user.email

      = f.label :password 
      = f.password_field :password, class: 'form-control' 
      
      = f.label :password_confirmation, t('.confirmation')
      = f.password_field :password_confirmation, class: 'form-control' 
      
      = f.submit t('.submit'), class: "btn btn-primary" 

app/views/password_resets/new.html.haml
- provide(:title, t('.title'))
%h1= t('.title')
.row
  .col-md-6.col-md-offset-3
    = form_for(:password_reset, url: password_resets_path) do |f| 
      
      = f.label :email 
      = f.email_field :email, class: 'form-control' 
      
      = f.submit t('.submit'), class: "btn btn-primary" 