config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'signup'         => 'users#new'
  post   'users/promote'  => 'users#change_admin'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'account_activations/edit'
  resources :account_activations, only: [:edit]

  get    'sessions/new'
  get    'login_as/:id' => 'sessions#login_as'
  get    'login'        => 'sessions#new'
  post   'login'        => 'sessions#create'
  delete 'logout'       => 'sessions#destroy'
  
  get    'users/:user_id/journal_entries' => 'journal_entries#index', as: :journal_entries
  post   'users/:user_id/journal_entries' => 'journal_entries#create'
  get    'users/:user_id/journal_entries/:id' => 'journal_entries#show', as: :journal_entry
  get    'users/:user_id/journal_entries/:id/edit' => 'journal_entries#edit', as: :edit_journal_entry
  patch  'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
#  put    'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
  delete 'users/:user_id/journal_entries/:id' => 'journal_entries#destroy', as: :delete_journal_entry
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :journal_entries

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)    
  end
  
  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sends new activation email.
  def send_new_activation_email
    create_activation_digest
    update_attribute(:activation_digest, User.digest(activation_token))
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  # Returns user's full name
  def full_name
    first_name + " " + last_name
  end

  private
    
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end
    
    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy, :change_admin, :activate_user]
  helper_method :sort_column, :sort_direction
  
  def index
    @users = User.order(sort_column + " " + sort_direction).paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    #if verify_recaptcha(model: @user) && @user.save
    if @user.save
      @user.send_activation_email
      add_flash_message( :info, t('.activation_email_notice') )
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      add_flash_message( :success, t('.update_success') )
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    add_flash_message( :success, t('.delete_success') )
    redirect_to users_url
  end
  
  def change_admin
    user = User.find(params[:user_id])
    if !current_user?(user)
      user.update_attributes(admin: !user.admin)
    end
    redirect_to user
  end

  def activate_user
    user = User.find(params[:user_id])
    if !current_user?(user)
      user.update_attributes(admin: !user.admin)
    end
    redirect_to user
  end

  private
    def user_params
      params.require(:user).permit(:first_name, 
                                   :last_name, 
                                   :email, 
                                   :password,
                                   :password_confirmation)
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_info.html.haml
= f.label :first_name, t('users.form_info.first_name'), class: 'required'
= f.text_field :first_name, class: 'form-control' 

= f.label :last_name, t('users.form_info.last_name'), class: 'required'
= f.text_field :last_name, class: 'form-control' 

= f.label :email, t('users.form_info.email'), class: 'required'
= f.email_field :email, class: 'form-control' 

= f.label :password, t('users.form_info.password'), class: 'required'
= f.password_field :password, class: 'form-control' 

= f.label :password_confirmation, t('users.form_info.password_confirm'), class: 'required'
= f.password_field :password_confirmation, class: 'form-control' 

app/views/users/_user.html.haml
%tr
  %td.nowrap
    = link_to user.first_name, user
  %td.nowrap
    = link_to user.last_name, user
  %td.nowrap
    = link_to user.email, user
  - if current_user.admin? && !current_user?(user)
    %td= link_to t('users.partial.delete'), user, method: :delete, data: { confirm: t('users.partial.confirm') }
  - else
    %td= ""

app/views/users/edit.html.haml
- provide(:title, t('.title'))

%h1= t('.header')

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f| 
      = render 'shared/error_messages', object: f.object 
      = render 'form_info', :f => f
      = f.submit t('.save'), class: "btn btn-primary" 

app/views/users/index.html.haml
- provide(:title, t('.title'))
.row
  .col-md-6.col-md-offset-3
    .panel.generic-panel
      .panel-heading
        %h3.panel-title.center= t('.title')
      %table.table
        %tr
          %th= sortable "first_name", t('.first_name')
          %th= sortable "last_name", t('.last_name')
          %th= sortable "email", t('.email')
          - if !current_user.nil? && current_user.admin?
            %th= t('.delete')
        = render @users
    .center
      = will_paginate

app/views/users/new.html.haml
- provide(:title, t('.title'))
%h1= t('.title')

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f| 
      = render 'shared/error_messages', object: f.object 
      = render 'form_info', :f => f
      = f.submit t('.create'), class: "btn btn-primary" 
      /= invisible_recaptcha_tags text: 'Create My Account', class: "btn btn-primary btn-block"

app/views/users/show.html.haml
- provide(:title, @user.first_name)
.row
  %aside.col-md-3
    .panel.generic-panel
      .panel-heading
        %h3.panel-title.center
          = t('.profile') + @user.full_name
      .panel-body
        %u 
          %b= t('.quick_links')
        %br
        %br
        - if current_user?(@user) || current_user.admin?
          %p
            = link_to t('.edit_profile'), edit_user_path(@user)
          %p
            = link_to @user.first_name + "'s Journal", journal_entries_url(user_id: @user)

  .col-md-6
    .panel.generic-panel
      .panel-heading
        %h3.panel-title.center= t('.profile_info')
      %table.table
        = table_row_helper(t('.first_name'), @user.first_name)
        = table_row_helper(t('.last_name'), @user.last_name)

  %aside.col-md-3
    - if !current_user.nil? && current_user.admin?
      .panel.admin-panel
        .panel-heading
          %h3.panel-title.center= t('.admin_panel')
        .panel-body
          - if !current_user?(@user)
            = link_to t('.login_as'), {controller: "sessions", action: "login_as"}, {class: "btn btn-warning center-block", role: "button"}
            %br
            = form_tag users_promote_path do
              = hidden_field_tag :user_id, @user.id
              - if @user.admin
                %input.btn.btn-danger{:type => "submit", :value => t('.demote'), data: { confirm: t('.demote_confirmation', :name => @user.full_name) }}
              - else
                %input.btn.btn-danger{:type => "submit", :value => t('.promote'), data: { confirm: t('.promote_confirmation', :name => @user.full_name) }}
          - else
            %p No available actions
            
            
            