config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'signup'         => 'users#new'
  post   'users/promote'  => 'users#change_admin'
  resources :users

  get 'password_resets/new'
  get 'password_resets/edit'
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'account_activations/edit'
  resources :account_activations, only: [:edit]

  get    'sessions/new'
  get    'login_as/:id' => 'sessions#login_as'
  get    'login'        => 'sessions#new'
  post   'login'        => 'sessions#create'
  delete 'logout'       => 'sessions#destroy'
  
  get    'users/:user_id/journal_entries' => 'journal_entries#index', as: :journal_entries
  post   'users/:user_id/journal_entries' => 'journal_entries#create'
  get    'users/:user_id/journal_entries/:id' => 'journal_entries#show', as: :journal_entry
  get    'users/:user_id/journal_entries/:id/edit' => 'journal_entries#edit', as: :edit_journal_entry
  patch  'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
#  put    'users/:user_id/journal_entries/:id' => 'journal_entries#update', as: :update_journal_entry
  delete 'users/:user_id/journal_entries/:id' => 'journal_entries#destroy', as: :delete_journal_entry
end

app/views/layouts/_footer.html.haml
%footer.footer.center
  %small.center
    = t('footer.copyright')

app/views/layouts/_header.html.haml
%nav.navbar.navbar-static-top.navbar-inverse
  .container
    .navbar-header
      = link_to t('application_title'), root_path, class: "navbar-brand", id: "logo"
      %button(type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-dropdown-1" aria-expanded="false")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse(id="nav-dropdown-1")
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to t('header.home'), root_path
        - if logged_in?
          %li= link_to "Journal", journal_entries_url(user_id: current_user)
          %li= link_to t('header.profile'), current_user
          %li.dropdown
            %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
              = t('header.dropdown_name')
              %b.caret
            %ul.dropdown-menu
              %li= link_to t('header.settings'), edit_user_path(current_user)
              %li.divider
              %li= link_to t('header.logout'), logout_path, method: :delete
          - if !current_user.nil? && current_user.admin?
            %li
              = link_to t('header.users'), users_path
        - else
          %li= link_to t('header.login'), login_path

app/views/layouts/application.html.haml
!!! 5

%html
  %head
  %title #{ full_title(yield(:title)) }
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, messages|
        .alert{:class => "alert-#{message_type}"}
          - messages.each do |msg|
            %ul
              %li
                = msg
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?